"""Host unit ownership is read from the composed CLAUDLOBBY_ROOT property."""

from pathlib import Path

from tests.conftest import call_script_fn

REPO_ROOT = Path(__file__).resolve().parent.parent
LIB_COMMON = REPO_ROOT / "claudlobby/_runtime_scripts" / "lib-common.sh"
JOB = "disk-monitor"


def _unit_text(root: str) -> str:
    """A composed host-job service unit."""
    return (
        "# Generated by claudlobby — do not hand-edit.\n"
        "[Unit]\n"
        f"Description=claudlobby {JOB} (host)\n\n"
        "[Service]\n"
        "Type=oneshot\n"
        f"WorkingDirectory={root}\n"
        f"Environment=CLAUDLOBBY_ROOT={root}\n"
        f"ExecStart={root}/lib/{JOB}.sh\n"
    )


class TestOwnerRootIsReadAsAProperty:
    """`unit_owner_root` reads the composer's CLAUDLOBBY_ROOT entry."""

    def _owner(self, path: Path) -> str:
        return call_script_fn(LIB_COMMON, "unit_owner_root", str(path)).strip()

    def test_reads_the_systemd_environment_entry(self, tmp_path):
        f = tmp_path / "u.service"
        f.write_text(_unit_text("/opt/rootA"))
        assert self._owner(f) == "/opt/rootA"

    def test_reads_the_launchd_plist_form_with_key_and_string_on_separate_lines(
        self, tmp_path
    ):
        # composer.py emits the timer plist across two lines; a one-line-only
        # matcher would report every macOS host unit as unowned during
        # the native ownership check.
        f = tmp_path / "u.plist"
        f.write_text(
            "<dict>\n"
            "  <key>EnvironmentVariables</key>\n"
            "  <dict>\n"
            "    <key>CLAUDLOBBY_ROOT</key>\n"
            "    <string>/opt/rootA</string>\n"
            "  </dict>\n"
            "</dict>\n"
        )
        assert self._owner(f) == "/opt/rootA"

    def test_a_unit_without_the_marker_reports_no_owner(self, tmp_path):
        # NOT guessed from ExecStart. A path prefix is a pattern standing in
        # for a property, and it silently re-scopes ownership the first time
        # the script layout moves.
        f = tmp_path / "u.service"
        f.write_text("[Service]\nExecStart=/opt/rootA/lib/disk-monitor.sh\n")
        assert self._owner(f) == ""

    def test_a_missing_file_reports_no_owner_rather_than_erroring(self, tmp_path):
        assert self._owner(tmp_path / "nope.service") == ""
