"""#1152 Layer 1 — host-job enrollment must refuse to capture another tree's unit.

Host units carry a FIXED, unprefixed identity (`claudlobby-disk-monitor`, …)
and live in one shared directory, so whichever root enrolls last owns them.
Enrollment was an unconditional copy: a second checkout running `setup-system`
silently re-pointed the production host's daily jobs at itself, and said
nothing. Reproduced on real systemd before this guard was written — tree B
captured tree A's unit at rc 0 with the normal success banner, and after the
second tree was deleted systemd reported the job `failed`.

The fixed identity is deliberate and stays (host equipment is one-per-host, not
one-per-fleet). What changes is that capture is refused rather than silent.

Ownership is read as a PROPERTY — the composer-emitted `CLAUDLOBBY_ROOT` entry
— never pattern-matched out of `ExecStart`. A unit whose owner cannot be
established is refused too, on its own message: guessing an owner from a path
prefix is how a script-layout change silently re-scopes who owns what.
"""

import os
import subprocess
from pathlib import Path

import pytest
from tests.conftest import call_script_fn, constructed_env

REPO_ROOT = Path(__file__).resolve().parent.parent
INSTALLER = REPO_ROOT / "lib" / "install_fleet_timer.sh"
LIB_COMMON = REPO_ROOT / "lib" / "lib-common.sh"

JOB = "disk-monitor"
UNIT = f"claudlobby-{JOB}"
REFUSE_RC = 3


def _unit_text(root: str) -> str:
    """A composed host-job service unit, as `claudlobby host-timers` emits it."""
    return (
        "# Generated by claudlobby — do not hand-edit.\n"
        "[Unit]\n"
        f"Description=claudlobby {JOB} (host)\n\n"
        "[Service]\n"
        "Type=oneshot\n"
        f"WorkingDirectory={root}\n"
        f"Environment=CLAUDLOBBY_ROOT={root}\n"
        f"ExecStart={root}/lib/{JOB}.sh\n"
    )


def _timer_text() -> str:
    return (
        "# Generated by claudlobby — do not hand-edit.\n"
        "[Unit]\n"
        f"Description=claudlobby {JOB} timer (host)\n\n"
        "[Timer]\n"
        "OnCalendar=*-*-* 05:00:00\n\n"
        "[Install]\n"
        "WantedBy=timers.target\n"
    )


@pytest.fixture
def host(tmp_path):
    """An isolated HOME with a stub systemctl, plus two composed trees.

    systemctl is stubbed rather than skipped: the guard has to run in the real
    script's control flow, and a real `enable --now` would touch this machine's
    live user units.
    """
    home = tmp_path / "home"
    (home / ".config" / "systemd" / "user").mkdir(parents=True)
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    stub = bin_dir / "systemctl"
    stub.write_text('#!/bin/bash\nprintf "%s\\n" "systemctl $*" >> "$SYSTEMCTL_LOG"\n')
    stub.chmod(0o755)

    trees = {}
    for name in ("A", "B"):
        root = tmp_path / f"tree{name}"
        timers = root / "runtime" / "_host" / "timers"
        timers.mkdir(parents=True)
        (timers / f"{UNIT}.service").write_text(_unit_text(str(root)))
        (timers / f"{UNIT}.timer").write_text(_timer_text())
        trees[name] = root

    return {
        "home": home,
        "units": home / ".config" / "systemd" / "user",
        "trees": trees,
        "log": tmp_path / "systemctl.log",
        "path": f"{bin_dir}:{os.environ.get('PATH', '')}",
    }


def _enroll(host, tree: str, *extra: str) -> subprocess.CompletedProcess:
    """setup-system phase 9's call shape: TIMER_DIR + UNIT_NAME overrides."""
    root = host["trees"][tree]
    env = constructed_env(
        HOME=str(host["home"]),
        PATH=host["path"],
        TIMER_DIR=str(root / "runtime" / "_host" / "timers"),
        UNIT_NAME=UNIT,
        SYSTEMCTL_LOG=str(host["log"]),
    )
    return subprocess.run(
        ["bash", str(INSTALLER), JOB, *extra],
        capture_output=True,
        text=True,
        env=env,
        timeout=60,
    )


def _installed(host) -> str:
    return (host["units"] / f"{UNIT}.service").read_text()


class TestOwnerRootIsReadAsAProperty:
    """`unit_owner_root` reads the composer's CLAUDLOBBY_ROOT entry."""

    def _owner(self, path: Path) -> str:
        return call_script_fn(LIB_COMMON, "unit_owner_root", str(path)).strip()

    def test_reads_the_systemd_environment_entry(self, tmp_path):
        f = tmp_path / "u.service"
        f.write_text(_unit_text("/opt/rootA"))
        assert self._owner(f) == "/opt/rootA"

    def test_reads_the_launchd_plist_form_with_key_and_string_on_separate_lines(
        self, tmp_path
    ):
        # composer.py emits the timer plist across two lines; a one-line-only
        # matcher would report every macOS host unit as unowned and refuse
        # every enrollment on that platform.
        f = tmp_path / "u.plist"
        f.write_text(
            "<dict>\n"
            "  <key>EnvironmentVariables</key>\n"
            "  <dict>\n"
            "    <key>CLAUDLOBBY_ROOT</key>\n"
            "    <string>/opt/rootA</string>\n"
            "  </dict>\n"
            "</dict>\n"
        )
        assert self._owner(f) == "/opt/rootA"

    def test_a_unit_without_the_marker_reports_no_owner(self, tmp_path):
        # NOT guessed from ExecStart. A path prefix is a pattern standing in
        # for a property, and it silently re-scopes ownership the first time
        # the script layout moves.
        f = tmp_path / "u.service"
        f.write_text("[Service]\nExecStart=/opt/rootA/lib/disk-monitor.sh\n")
        assert self._owner(f) == ""

    def test_a_missing_file_reports_no_owner_rather_than_erroring(self, tmp_path):
        assert self._owner(tmp_path / "nope.service") == ""


class TestEnrollmentRefusesCapture:
    def test_first_enrollment_succeeds(self, host):
        r = _enroll(host, "A")
        assert r.returncode == 0, r.stderr
        assert str(host["trees"]["A"]) in _installed(host)

    def test_reenrolling_from_the_owning_root_stays_frictionless(self, host):
        assert _enroll(host, "A").returncode == 0
        r = _enroll(host, "A")
        assert r.returncode == 0, r.stderr
        assert "refus" not in (r.stdout + r.stderr).lower()

    def test_a_second_root_is_refused_and_changes_nothing_on_disk(self, host):
        assert _enroll(host, "A").returncode == 0
        before = _installed(host)
        before_timer = (host["units"] / f"{UNIT}.timer").read_text()

        r = _enroll(host, "B")

        assert r.returncode == REFUSE_RC, f"expected refusal, got {r.returncode}"
        out = r.stdout + r.stderr
        assert str(host["trees"]["A"]) in out, "must name the owning root"
        assert str(host["trees"]["B"]) in out, "must name the enrolling root"
        assert UNIT in out, "must name the unit"
        # The acceptance criterion: refuse AND change nothing.
        assert _installed(host) == before
        assert (host["units"] / f"{UNIT}.timer").read_text() == before_timer

    def test_a_refused_enrollment_does_not_touch_systemd(self, host):
        assert _enroll(host, "A").returncode == 0
        host["log"].write_text("")
        _enroll(host, "B")
        # No daemon-reload, no enable: refusing after mutating the unit state
        # would be a different bug wearing the fix's clothes.
        assert host["log"].read_text().strip() == ""

    def test_adopt_takes_ownership_and_says_what_it_took(self, host):
        # Asserting only that B ends up owning the unit would be DECORATIVE:
        # that is exactly what the unfixed tree does, so the test would pass
        # before and after and gate nothing. What only the guard can produce is
        # an explicit notice naming the root being displaced.
        assert _enroll(host, "A").returncode == 0
        r = _enroll(host, "B", "--adopt")
        assert r.returncode == 0, r.stderr
        assert str(host["trees"]["B"]) in _installed(host)
        out = r.stdout + r.stderr
        assert "adopt" in out.lower(), "adoption must be announced, not silent"
        assert str(host["trees"]["A"]) in out, "must name the displaced root"

    def test_when_neither_side_carries_a_marker_it_proceeds_but_says_so(self, host):
        # The one permissive branch, pinned so it cannot widen silently. With
        # no marker on EITHER side no ownership judgement is possible in any
        # direction, and refusing would turn a guard against capture into a
        # refusal to install anything — which is what an earlier version of
        # this guard did, taking 17 setup-backbone tests down with it.
        # Reachable only for units this system did not write: every
        # composer-emitted unit carries the marker.
        (host["units"] / f"{UNIT}.service").write_text("[Service]\nExecStart=/x/y.sh\n")
        src = host["trees"]["A"] / "runtime" / "_host" / "timers"
        (src / f"{UNIT}.service").write_text("[Service]\nExecStart=/p/q.sh\n")

        r = _enroll(host, "A")

        assert r.returncode == 0, r.stderr
        out = (r.stdout + r.stderr).lower()
        assert "no claudlobby_root marker" in out, "the guard went inert silently"

    def test_an_unowned_unit_is_refused_on_its_own_message(self, host):
        # Pre-existing unit with no ownership marker: the owner cannot be
        # established, so it is refused rather than assumed to be ours.
        (host["units"] / f"{UNIT}.service").write_text(
            "[Service]\nExecStart=/somewhere/lib/disk-monitor.sh\n"
        )
        r = _enroll(host, "A")
        assert r.returncode == REFUSE_RC
        out = (r.stdout + r.stderr).lower()
        assert "owner" in out or "unowned" in out or "cannot" in out
        assert "--adopt" in r.stdout + r.stderr
