"""#1094 / #1152 Layer 2 — the cold-start harness's first test wrapper.

`coldstart-harness.sh` had no test coverage at all (#1094). This file opens it
on the property #1152 needs: the harness must be able to undo a host-unit
capture it cannot prevent.

Why the harness needs its own belt when Layer 1 exists: the harness runs an
ARBITRARY ref by design, and that tree may predate the enrollment guard. It
cannot rely on the code under test defending itself.

Why the existing snapshot cannot do it: `snap_unit_files` records unit
NAMES. `reap` removes what is ABSENT from that list, which is correct — a
pre-existing production unit must never be deleted. But an overwritten unit is
still present, so it is correctly not removed, and the capture survives the
reap. Identity is the wrong grain for this; only content closes it.
"""

import os
import subprocess
from pathlib import Path

import pytest
from tests.conftest import constructed_env

REPO_ROOT = Path(__file__).resolve().parent.parent
HARNESS = REPO_ROOT / "lib" / "coldstart-harness.sh"

OWNED = "/opt/production-root"
FOREIGN = "/tmp/cold-arm-tree"


def _host_unit(root: str, job: str = "disk-monitor") -> str:
    return (
        "# Generated by claudlobby — do not hand-edit.\n"
        "[Unit]\n"
        f"Description=claudlobby {job} (host)\n\n"
        "[Service]\n"
        "Type=oneshot\n"
        f"Environment=CLAUDLOBBY_ROOT={root}\n"
        f"ExecStart={root}/lib/{job}.sh\n"
    )


@pytest.fixture
def host(tmp_path):
    """Isolated HOME + harness state dir, with stub systemctl/tmux on PATH."""
    home = tmp_path / "home"
    units = home / ".config" / "systemd" / "user"
    units.mkdir(parents=True)
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    for tool in ("systemctl", "tmux", "launchctl", "pgrep"):
        p = bin_dir / tool
        p.write_text("#!/bin/bash\nexit 0\n")
        p.chmod(0o755)

    # Two pre-existing production host units — the population reap must never
    # delete and (after this change) must restore if the run overwrote them.
    (units / "claudlobby-disk-monitor.service").write_text(_host_unit(OWNED))
    (units / "claudlobby-claude-update.service").write_text(
        _host_unit(OWNED, "update-claude-code")
    )

    return {
        "home": home,
        "units": units,
        "state": tmp_path / "state",
        "path": f"{bin_dir}:{os.environ.get('PATH', '')}",
    }


def _call(host, snippet: str, *args: str) -> subprocess.CompletedProcess:
    env = constructed_env(
        HOME=str(host["home"]),
        PATH=host["path"],
        COLDSTART_STATE_DIR=str(host["state"]),
    )
    return subprocess.run(
        ["bash", "-c", f'. "{HARNESS}"; {snippet}', "_", *args],
        capture_output=True,
        text=True,
        env=env,
        timeout=60,
    )


class TestHostUnitContentIsSnapshotted:
    def test_snapshot_records_content_not_only_names(self, host):
        r = _call(host, "write_snapshot")
        assert r.returncode == 0, r.stderr
        saved = host["state"] / "snapshot" / "hostunits"
        assert saved.is_dir(), "no content snapshot — names alone cannot restore"
        assert (saved / "claudlobby-disk-monitor.service").read_text() == _host_unit(
            OWNED
        )

    def test_snapshot_says_how_many_host_units_it_is_guarding(self, host):
        r = _call(host, "write_snapshot")
        out = r.stdout + r.stderr
        assert "host unit" in out.lower(), (
            "the operator must be told these exist BEFORE the blind arm runs — "
            "they are the ones a capture would silently re-point"
        )


class TestReapRestoresCapturedUnits:
    def test_a_unit_the_run_overwrote_is_restored_to_its_original_bytes(self, host):
        _call(host, "write_snapshot")
        target = host["units"] / "claudlobby-disk-monitor.service"
        target.write_text(_host_unit(FOREIGN))  # the cold arm captures it

        r = _call(host, "restore_captured_host_units")

        assert r.returncode == 0, r.stderr
        assert target.read_text() == _host_unit(OWNED), "capture survived the reap"
        assert "claudlobby-disk-monitor.service" in (r.stdout + r.stderr), (
            "a silent restore is its own problem — the operator needs to know "
            "the run captured a production unit"
        )

    def test_an_untouched_unit_is_left_alone_and_not_reported(self, host):
        _call(host, "write_snapshot")
        target = host["units"] / "claudlobby-claude-update.service"
        before = target.stat().st_mtime_ns

        r = _call(host, "restore_captured_host_units")

        # rc asserted first, and deliberately: a function that does not exist
        # also touches nothing, so without this the test passes on the unfixed
        # tree and gates nothing.
        assert r.returncode == 0, r.stderr
        assert target.stat().st_mtime_ns == before, "rewrote a unit that never changed"
        assert "claudlobby-claude-update.service" not in (r.stdout + r.stderr)

    def test_a_unit_deleted_by_the_run_is_restored_too(self, host):
        # Deletion is capture's sibling: the unit is equally gone from
        # production, and equally invisible to a name-based reap that only ever
        # REMOVES things.
        _call(host, "write_snapshot")
        target = host["units"] / "claudlobby-disk-monitor.service"
        target.unlink()

        _call(host, "restore_captured_host_units")

        assert target.exists(), "a host unit the run deleted was not put back"
        assert target.read_text() == _host_unit(OWNED)

    def test_restoring_does_not_resurrect_a_unit_the_run_created(self, host):
        # Restore must only ever put back what it snapshotted. A unit born
        # during the run is reap's job to REMOVE, and a restore pass that
        # recreated it would fight the existing behaviour.
        _call(host, "write_snapshot")
        born = host["units"] / "claudlobby-brand-new.service"
        born.write_text(_host_unit(FOREIGN, "brand-new"))

        r = _call(host, "restore_captured_host_units")

        assert r.returncode == 0, r.stderr  # same reason as above
        assert born.read_text() == _host_unit(FOREIGN, "brand-new"), (
            "restore touched a unit it never snapshotted"
        )
