"""#1094 / #1152 Layer 2 — the cold-start harness's first test wrapper.

`coldstart-harness.sh` had no test coverage at all (#1094). This file opens it
on the property #1152 needs: the harness must be able to undo a host-unit
capture it cannot prevent.

Why the harness needs its own belt when Layer 1 exists: the harness runs an
ARBITRARY ref by design, and that tree may predate the enrollment guard. It
cannot rely on the code under test defending itself.

Why the existing snapshot cannot do it: `snap_unit_files` records unit
NAMES. `reap` removes what is ABSENT from that list, which is correct — a
pre-existing production unit must never be deleted. But an overwritten unit is
still present, so it is correctly not removed, and the capture survives the
reap. Identity is the wrong grain for this; only content closes it.
"""

import os
import plistlib
import subprocess
from pathlib import Path

import pytest
from tests.conftest import constructed_env

REPO_ROOT = Path(__file__).resolve().parent.parent
HARNESS = REPO_ROOT / "lib" / "coldstart-harness.sh"

OWNED = "/opt/production-root"
FOREIGN = "/tmp/cold-arm-tree"


def _host_unit(root: str, job: str = "disk-monitor") -> str:
    return (
        "# Generated by claudlobby — do not hand-edit.\n"
        "[Unit]\n"
        f"Description=claudlobby {job} (host)\n\n"
        "[Service]\n"
        "Type=oneshot\n"
        f"Environment=CLAUDLOBBY_ROOT={root}\n"
        f"ExecStart={root}/lib/{job}.sh\n"
    )


@pytest.fixture
def host(tmp_path):
    """An explicit Linux fixture on either native test platform.

    The service files below model systemd. Feed that kernel name through the
    real detect_os door; ambient Darwin would make the harness look elsewhere.
    """
    home = tmp_path / "home"
    units = home / ".config" / "systemd" / "user"
    units.mkdir(parents=True)
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    for tool in ("systemctl", "tmux", "launchctl", "pgrep"):
        p = bin_dir / tool
        p.write_text(
            "#!/bin/bash\n"
            f"printf '%s\\t%s\\n' '{tool}' \"$*\" >> \"$COLDSTART_CALLS\"\n"
            "exit 0\n"
        )
        p.chmod(0o755)
    uname = bin_dir / "uname"
    uname.write_text("#!/bin/bash\nprintf '%s\\n' Linux\n")
    uname.chmod(0o755)

    # Two pre-existing production host units — the population reap must never
    # delete and (after this change) must restore if the run overwrote them.
    (units / "claudlobby-disk-monitor.service").write_text(_host_unit(OWNED))
    (units / "claudlobby-claude-update.service").write_text(
        _host_unit(OWNED, "update-claude-code")
    )

    return {
        "home": home,
        "units": units,
        "state": tmp_path / "state",
        "bin": bin_dir,
        "calls": tmp_path / "calls.log",
        "path": f"{bin_dir}:{os.environ.get('PATH', '')}",
    }


def _call(host, snippet: str, *args: str) -> subprocess.CompletedProcess:
    env = constructed_env(
        HOME=str(host["home"]),
        PATH=host["path"],
        COLDSTART_STATE_DIR=str(host["state"]),
        COLDSTART_CALLS=str(host["calls"]),
    )
    return subprocess.run(
        ["bash", "-c", f'. "{HARNESS}"; {snippet}', "_", *args],
        capture_output=True,
        text=True,
        env=env,
        timeout=60,
    )


class TestHostUnitContentIsSnapshotted:
    def test_snapshot_records_content_not_only_names(self, host):
        r = _call(host, "write_snapshot")
        assert r.returncode == 0, r.stderr
        saved = host["state"] / "snapshot" / "hostunits"
        assert saved.is_dir(), "no content snapshot — names alone cannot restore"
        assert (saved / "claudlobby-disk-monitor.service").read_text() == _host_unit(
            OWNED
        )

    def test_snapshot_says_how_many_host_units_it_is_guarding(self, host):
        r = _call(host, "write_snapshot")
        out = r.stdout + r.stderr
        assert "host unit" in out.lower(), (
            "the operator must be told these exist BEFORE the blind arm runs — "
            "they are the ones a capture would silently re-point"
        )


class TestSnapshotSurvivesAFreshHost:
    """A missing directory is not an error — it is the fresh host, which is the
    whole point of this harness.

    `2>/dev/null` did not say that: lib-common turns on `pipefail`, so `ls` of
    a directory that does not exist failed the pipeline, `set -e` aborted the
    snapshot, and the redirect made it abort SILENTLY at rc 2. It survived
    because a developer machine always has a tmux socket dir and a user unit
    dir; CI has neither, and reproduced it exactly.
    """

    def test_snapshot_succeeds_with_no_user_unit_directory_at_all(self, host):
        import shutil

        shutil.rmtree(host["units"])
        r = _call(host, "write_snapshot")
        assert r.returncode == 0, f"rc={r.returncode} stderr={r.stderr!r}"
        assert (host["state"] / "snapshot" / "unitfiles.txt").read_text() == ""

    def test_snapshot_succeeds_when_no_host_units_exist(self, host):
        for f in host["units"].glob("claudlobby-*"):
            f.unlink()
        r = _call(host, "write_snapshot")
        assert r.returncode == 0, f"rc={r.returncode} stderr={r.stderr!r}"


class TestReapRestoresCapturedUnits:
    def test_a_unit_the_run_overwrote_is_restored_to_its_original_bytes(self, host):
        _call(host, "write_snapshot")
        target = host["units"] / "claudlobby-disk-monitor.service"
        target.write_text(_host_unit(FOREIGN))  # the cold arm captures it

        r = _call(host, "restore_captured_host_units")

        assert r.returncode == 0, r.stderr
        assert target.read_text() == _host_unit(OWNED), "capture survived the reap"
        assert "claudlobby-disk-monitor.service" in (r.stdout + r.stderr), (
            "a silent restore is its own problem — the operator needs to know "
            "the run captured a production unit"
        )

    def test_an_untouched_unit_is_left_alone_and_not_reported(self, host):
        _call(host, "write_snapshot")
        target = host["units"] / "claudlobby-claude-update.service"
        before = target.stat().st_mtime_ns

        r = _call(host, "restore_captured_host_units")

        # rc asserted first, and deliberately: a function that does not exist
        # also touches nothing, so without this the test passes on the unfixed
        # tree and gates nothing.
        assert r.returncode == 0, r.stderr
        assert target.stat().st_mtime_ns == before, "rewrote a unit that never changed"
        assert "claudlobby-claude-update.service" not in (r.stdout + r.stderr)

    def test_a_unit_deleted_by_the_run_is_restored_too(self, host):
        # Deletion is capture's sibling: the unit is equally gone from
        # production, and equally invisible to a name-based reap that only ever
        # REMOVES things.
        _call(host, "write_snapshot")
        target = host["units"] / "claudlobby-disk-monitor.service"
        target.unlink()

        _call(host, "restore_captured_host_units")

        assert target.exists(), "a host unit the run deleted was not put back"
        assert target.read_text() == _host_unit(OWNED)

    def test_restoring_does_not_resurrect_a_unit_the_run_created(self, host):
        # Restore must only ever put back what it snapshotted. A unit born
        # during the run is reap's job to REMOVE, and a restore pass that
        # recreated it would fight the existing behaviour.
        _call(host, "write_snapshot")
        born = host["units"] / "claudlobby-brand-new.service"
        born.write_text(_host_unit(FOREIGN, "brand-new"))

        r = _call(host, "restore_captured_host_units")

        assert r.returncode == 0, r.stderr  # same reason as above
        assert born.read_text() == _host_unit(FOREIGN, "brand-new"), (
            "restore touched a unit it never snapshotted"
        )


DARWIN_LABEL = "claudlobby-disk-monitor"
DARWIN_OTHER = "claudlobby-claude-update"


def _launch_agent(root: str, label: str = DARWIN_LABEL) -> bytes:
    return plistlib.dumps({
        "Label": label,
        "ProgramArguments": [f"{root}/lib/disk-monitor.sh"],
        "EnvironmentVariables": {"CLAUDLOBBY_ROOT": root},
    })


@pytest.fixture
def darwin_host(host):
    """Exercise the Darwin branch with private files and a logged manager stub.

    Keep the Linux fixture files as decoys: using the wrong unit directory must
    fail, even when both directories exist. This is a branch contract test,
    not native launchd lifecycle evidence.
    """
    (host["bin"] / "uname").write_text("#!/bin/bash\nprintf '%s\\n' Darwin\n")
    (host["bin"] / "launchctl").write_text(
        "#!/bin/bash\n"
        "printf 'launchctl\\t%s\\n' \"$*\" >> \"$COLDSTART_CALLS\"\n"
        "[ \"$*\" = list ] || exit 97\n"
        "printf 'PID\\tStatus\\tLabel\\n'\n"
        f"printf '%s\\n' '- 0 {DARWIN_LABEL}' '- 0 {DARWIN_OTHER}'\n"
    )
    units = host["home"] / "Library" / "LaunchAgents"
    units.mkdir(parents=True)
    (units / f"{DARWIN_LABEL}.plist").write_bytes(_launch_agent(OWNED))
    (units / f"{DARWIN_OTHER}.plist").write_bytes(_launch_agent(OWNED, DARWIN_OTHER))
    return {**host, "linux_units": host["units"], "units": units}


class TestDarwinHostUnitSnapshots:
    def test_snapshot_uses_private_launch_agents_and_launchctl(self, darwin_host):
        r = _call(darwin_host, "write_snapshot")
        assert r.returncode == 0, r.stderr
        snapshot = darwin_host["state"] / "snapshot"
        names = sorted([f"{DARWIN_LABEL}.plist", f"{DARWIN_OTHER}.plist"])
        assert sorted(p.name for p in (snapshot / "hostunits").iterdir()) == names
        for label in (DARWIN_LABEL, DARWIN_OTHER):
            assert (snapshot / "hostunits" / f"{label}.plist").read_bytes() == (
                _launch_agent(OWNED, label)
            )
        assert (snapshot / "unitfiles.txt").read_text().splitlines() == names
        assert (snapshot / "units.txt").read_text().splitlines() == sorted([
            DARWIN_LABEL, DARWIN_OTHER,
        ])
        assert darwin_host["calls"].read_text().splitlines() == ["launchctl\tlist"]
        assert "2 pre-existing claudlobby-* host unit(s)" in r.stdout

    @pytest.mark.parametrize("change", ["overwrite", "delete"])
    def test_restore_puts_back_the_original_plist_bytes(self, darwin_host, change):
        snapshot = _call(darwin_host, "write_snapshot")
        assert snapshot.returncode == 0, snapshot.stderr
        target = darwin_host["units"] / f"{DARWIN_LABEL}.plist"
        if change == "overwrite":
            target.write_bytes(_launch_agent(FOREIGN))
        else:
            target.unlink()

        r = _call(darwin_host, "restore_captured_host_units")

        assert r.returncode == 0, r.stderr
        assert target.read_bytes() == _launch_agent(OWNED)
        assert f"{DARWIN_LABEL}.plist" in r.stdout
        # Restoring files does not mutate the supervisor or the other OS tree.
        assert darwin_host["calls"].read_text().splitlines() == ["launchctl\tlist"]
        linux = darwin_host["linux_units"] / "claudlobby-disk-monitor.service"
        assert linux.read_text() == _host_unit(OWNED)

    def test_restore_leaves_untouched_and_new_plists_alone(self, darwin_host):
        snapshot = _call(darwin_host, "write_snapshot")
        assert snapshot.returncode == 0, snapshot.stderr
        original = darwin_host["units"] / f"{DARWIN_LABEL}.plist"
        before = original.stat().st_mtime_ns
        born = darwin_host["units"] / "claudlobby-brand-new.plist"
        born.write_bytes(_launch_agent(FOREIGN, "claudlobby-brand-new"))

        r = _call(darwin_host, "restore_captured_host_units")

        assert r.returncode == 0, r.stderr
        assert original.stat().st_mtime_ns == before
        assert original.read_bytes() == _launch_agent(OWNED)
        assert born.read_bytes() == _launch_agent(FOREIGN, "claudlobby-brand-new")
        assert "RESTORED" not in r.stdout + r.stderr
        assert darwin_host["calls"].read_text().splitlines() == ["launchctl\tlist"]
