"""#1094 / #1152 Layer 2 — the cold-start harness's first test wrapper.

`coldstart-harness.sh` had no test coverage at all (#1094). This file opens it
on the property #1152 needs: the harness must be able to undo a host-unit
capture it cannot prevent.

Why the harness needs its own belt when Layer 1 exists: the harness runs an
ARBITRARY ref by design, and that tree may predate the enrollment guard. It
cannot rely on the code under test defending itself.

Why the existing snapshot cannot do it: `snap_unit_files` records unit
NAMES. `reap` removes what is ABSENT from that list, which is correct — a
pre-existing production unit must never be deleted. But an overwritten unit is
still present, so it is correctly not removed, and the capture survives the
reap. Identity is the wrong grain for this; only content closes it.
"""

import os
import subprocess
from pathlib import Path

import pytest
from tests.conftest import constructed_env

REPO_ROOT = Path(__file__).resolve().parent.parent
HARNESS = REPO_ROOT / "harness" / "coldstart-harness.sh"

OWNED = "/opt/production-root"
FOREIGN = "/tmp/cold-arm-tree"


def _host_unit(root: str, job: str = "disk-monitor") -> str:
    return (
        "# Generated by claudlobby — do not hand-edit.\n"
        "[Unit]\n"
        f"Description=claudlobby {job} (host)\n\n"
        "[Service]\n"
        "Type=oneshot\n"
        f"Environment=CLAUDLOBBY_ROOT={root}\n"
        f"ExecStart={root}/lib/{job}.sh\n"
    )


@pytest.fixture
def host(tmp_path):
    """Isolated systemd HOME + harness state dir, independent of the test host."""
    home = tmp_path / "home"
    units = home / ".config" / "systemd" / "user"
    units.mkdir(parents=True)
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    # Snapshot/restore must select the systemd directory seeded below.
    uname = bin_dir / "uname"
    uname.write_text('#!/bin/bash\nprintf "Linux\\n"\n')
    uname.chmod(0o755)
    for tool in ("systemctl", "tmux", "launchctl", "pgrep"):
        p = bin_dir / tool
        p.write_text("#!/bin/bash\nexit 0\n")
        p.chmod(0o755)

    # Two pre-existing production host units — the population reap must never
    # delete and (after this change) must restore if the run overwrote them.
    (units / "claudlobby-disk-monitor.service").write_text(_host_unit(OWNED))
    (units / "claudlobby-claude-update.service").write_text(
        _host_unit(OWNED, "update-claude-code")
    )

    return {
        "home": home,
        "units": units,
        "state": tmp_path / "state",
        "path": f"{bin_dir}:{os.environ.get('PATH', '')}",
    }


def _call(host, snippet: str, *args: str) -> subprocess.CompletedProcess:
    env = constructed_env(
        HOME=str(host["home"]),
        PATH=host["path"],
        COLDSTART_STATE_DIR=str(host["state"]),
    )
    return subprocess.run(
        ["bash", "-c", f'. "{HARNESS}"; {snippet}', "_", *args],
        capture_output=True,
        text=True,
        env=env,
        timeout=60,
    )


class TestHostUnitContentIsSnapshotted:
    def test_snapshot_records_content_not_only_names(self, host):
        r = _call(host, "write_snapshot")
        assert r.returncode == 0, r.stderr
        saved = host["state"] / "snapshot" / "hostunits"
        assert saved.is_dir(), "no content snapshot — names alone cannot restore"
        assert (saved / "claudlobby-disk-monitor.service").read_text() == _host_unit(
            OWNED
        )

    def test_snapshot_says_how_many_host_units_it_is_guarding(self, host):
        r = _call(host, "write_snapshot")
        out = r.stdout + r.stderr
        assert "host unit" in out.lower(), (
            "the operator must be told these exist BEFORE the blind arm runs — "
            "they are the ones a capture would silently re-point"
        )


class TestSnapshotSurvivesAFreshHost:
    """A missing directory is not an error — it is the fresh host, which is the
    whole point of this harness.

    `2>/dev/null` did not say that: lib-common turns on `pipefail`, so `ls` of
    a directory that does not exist failed the pipeline, `set -e` aborted the
    snapshot, and the redirect made it abort SILENTLY at rc 2. It survived
    because a developer machine always has a tmux socket dir and a user unit
    dir; CI has neither, and reproduced it exactly.
    """

    def test_snapshot_succeeds_with_no_user_unit_directory_at_all(self, host):
        import shutil

        shutil.rmtree(host["units"])
        r = _call(host, "write_snapshot")
        assert r.returncode == 0, f"rc={r.returncode} stderr={r.stderr!r}"
        assert (host["state"] / "snapshot" / "unitfiles.txt").read_text() == ""

    def test_snapshot_succeeds_when_no_host_units_exist(self, host):
        for f in host["units"].glob("claudlobby-*"):
            f.unlink()
        r = _call(host, "write_snapshot")
        assert r.returncode == 0, f"rc={r.returncode} stderr={r.stderr!r}"


class TestReapRestoresCapturedUnits:
    def test_a_unit_the_run_overwrote_is_restored_to_its_original_bytes(self, host):
        _call(host, "write_snapshot")
        target = host["units"] / "claudlobby-disk-monitor.service"
        target.write_text(_host_unit(FOREIGN))  # the cold arm captures it

        r = _call(host, "restore_captured_host_units")

        assert r.returncode == 0, r.stderr
        assert target.read_text() == _host_unit(OWNED), "capture survived the reap"
        assert "claudlobby-disk-monitor.service" in (r.stdout + r.stderr), (
            "a silent restore is its own problem — the operator needs to know "
            "the run captured a production unit"
        )

    def test_an_untouched_unit_is_left_alone_and_not_reported(self, host):
        _call(host, "write_snapshot")
        target = host["units"] / "claudlobby-claude-update.service"
        before = target.stat().st_mtime_ns

        r = _call(host, "restore_captured_host_units")

        # rc asserted first, and deliberately: a function that does not exist
        # also touches nothing, so without this the test passes on the unfixed
        # tree and gates nothing.
        assert r.returncode == 0, r.stderr
        assert target.stat().st_mtime_ns == before, "rewrote a unit that never changed"
        assert "claudlobby-claude-update.service" not in (r.stdout + r.stderr)

    def test_a_unit_deleted_by_the_run_is_restored_too(self, host):
        # Deletion is capture's sibling: the unit is equally gone from
        # production, and equally invisible to a name-based reap that only ever
        # REMOVES things.
        _call(host, "write_snapshot")
        target = host["units"] / "claudlobby-disk-monitor.service"
        target.unlink()

        _call(host, "restore_captured_host_units")

        assert target.exists(), "a host unit the run deleted was not put back"
        assert target.read_text() == _host_unit(OWNED)

    def test_restoring_does_not_resurrect_a_unit_the_run_created(self, host):
        # Restore must only ever put back what it snapshotted. A unit born
        # during the run is reap's job to REMOVE, and a restore pass that
        # recreated it would fight the existing behaviour.
        _call(host, "write_snapshot")
        born = host["units"] / "claudlobby-brand-new.service"
        born.write_text(_host_unit(FOREIGN, "brand-new"))

        r = _call(host, "restore_captured_host_units")

        assert r.returncode == 0, r.stderr  # same reason as above
        assert born.read_text() == _host_unit(FOREIGN, "brand-new"), (
            "restore touched a unit it never snapshotted"
        )


# --- #2002: the launch line, the root fence, and an honest status -----------------


def _settings(host, body: str) -> None:
    d = host["home"] / ".claude"
    d.mkdir(parents=True, exist_ok=True)
    (d / "settings.json").write_text(body)


def _stub(host, tool: str, body: str) -> None:
    p = Path(host["path"].split(":")[0]) / tool
    p.write_text("#!/bin/bash\n" + body + "\n")
    p.chmod(0o755)


class TestTheLaunchLineLoadsNoUserSettings:
    """A plain `claude` loads the user's settings. On the #2002 host those held a
    bare `Bash` allow rule and `defaultMode: auto`, beside passwordless sudo, so a
    blind run could have changed the host as root without a single prompt."""

    def test_prepare_prints_the_safe_launch_line(self, host):
        r = _call(host, 'print_launch /tmp/some-tree')
        assert r.returncode == 0, r.stderr
        assert "claude --setting-sources project,local --strict-mcp-config" in r.stdout
        assert 'cd /tmp/some-tree && PATH="' in r.stdout
        assert f'{host["state"]}/fence:$PATH' in r.stdout

    def test_prepare_writes_the_fence_and_prints_the_line_that_uses_it(self, host, tmp_path):
        # `cmd_prepare` is the one place that joins the two: a fence it did not
        # write would leave the printed line naming a directory with no `sudo`.
        _stub(
            host,
            "git",
            """case "$*" in
  *"rev-parse --verify"*) exit 0 ;;
  *"rev-parse"*) echo 0123456789abcdef0123456789abcdef01234567 ;;
  *"archive"*) tar -c -T /dev/null ;;
esac""",
        )
        r = _call(host, f'cmd_prepare --dir "{tmp_path / "tree"}"')
        fence = host["state"] / "fence" / "sudo"
        assert r.returncode == 0, r.stderr
        assert fence.is_file() and os.access(fence, os.X_OK), "prepare did not write the fence"
        assert f'PATH="{fence.parent}:$PATH" claude --setting-sources project,local --strict-mcp-config' in r.stdout, (
            r.stdout
        )

    def test_the_fence_refuses_sudo_loudly(self, host):
        # The harness runs under `set -e`, so capture the refusal's code with `||`.
        r = _call(host, 'write_fence; "$COLDSTART_STATE_DIR/fence/sudo" true || echo "rc=$?"')
        assert "rc=1" in r.stdout
        assert "refused by the cold-start fence" in r.stderr


class TestPreflightNamesWhatALaunchWouldInherit:
    @pytest.mark.parametrize("rule", ["Bash", "Bash(*)", "Bash(:*)"])
    def test_an_allow_every_command_rule_is_warned(self, host, rule):
        _settings(host, '{"permissions": {"allow": ["Bash(git *)", "%s"]}}' % rule)
        r = _call(host, "preflight")
        assert "allow every shell command" in r.stdout

    def test_bypass_permissions_as_the_default_mode_is_warned(self, host):
        _settings(host, '{"permissions": {"defaultMode": "bypassPermissions"}}')
        r = _call(host, "preflight")
        assert "allow every shell command" in r.stdout

    def test_narrow_allow_rules_are_not_warned(self, host):
        _settings(host, '{"permissions": {"allow": ["Bash(git *)", "Bash(ls *)"]}}')
        r = _call(host, "preflight")
        assert "allow every shell command" not in r.stdout

    def test_passwordless_sudo_is_warned(self, host):
        _stub(host, "sudo", '[ "$1" = "-n" ] && exit 0; exit 1')
        r = _call(host, "preflight")
        assert "sudo runs here without a password" in r.stdout

    def test_sudo_that_needs_a_password_is_not_warned(self, host):
        _stub(host, "sudo", "exit 1")
        r = _call(host, "preflight")
        assert "sudo runs here without a password" not in r.stdout


class TestStatusDoesNotTripTheErrorTrap:
    """`pgrep` exits 1 when nothing matches; under `pipefail` the unguarded count
    failed its substitution, and the inherited ERR trap recorded a false
    `script_error` ("non-zero exit at line 286") on every clean run."""

    def test_no_process_referencing_the_tree_is_a_zero_not_a_script_error(self, host, tmp_path):
        _stub(host, "pgrep", "exit 1")
        snap = host["state"] / "snapshot"
        snap.mkdir(parents=True)
        for kind in ("units", "unitfiles", "sockets"):
            (snap / f"{kind}.txt").write_text("")
        (host["state"] / "run.env").write_text(f"tree={tmp_path / 'gone-tree'}\n")
        r = _call(
            host,
            'emit_script_error() { printf "SCRIPT_ERROR %s\\n" "$4" >&2; }; cmd_status',
        )
        assert "processes referencing the tree: 0" in r.stdout, r.stdout + r.stderr
        assert "SCRIPT_ERROR" not in r.stderr, r.stderr

    def test_processes_referencing_the_tree_are_counted(self, host, tmp_path):
        _stub(host, "pgrep", "printf '111\\n222\\n'")
        snap = host["state"] / "snapshot"
        snap.mkdir(parents=True)
        for kind in ("units", "unitfiles", "sockets"):
            (snap / f"{kind}.txt").write_text("")
        (host["state"] / "run.env").write_text(f"tree={tmp_path / 'gone-tree'}\n")
        r = _call(host, "cmd_status")
        assert "processes referencing the tree: 2" in r.stdout, r.stdout + r.stderr
