#!/bin/bash
# Install fleet automation as cron jobs (cross-platform: Linux + macOS).
#
# Generates crontab entries for:
#   - Per-bot keepalive (every 30 min, staggered across bots)
#   - Weekly log rotation
#   - Daily disk-usage monitor
#   - Optional daily creds-check
#
# Idempotent: existing claudlobby-managed lines are bracketed with
# `# BEGIN claudlobby:<fleet>` / `# END claudlobby:<fleet>` markers and
# replaced on re-run. Anything outside that block is preserved.
#
# Usage:
#   install-cron.sh [--fleet <name>] [--no-creds-check] [--dry-run]
#
# Discovers bots from $CLAUDLOBBY_ROOT/local/<fleet>/runtime/bots/. Run
# `claudlobby --fleet <name> generate` first.
set -euo pipefail

LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib-common.sh
. "$LIB_DIR/lib-common.sh"
install_error_trap ""

FLEET="${CLAUDLOBBY_FLEET:-}"
NO_CREDS_CHECK=0
DRY_RUN=0

while [ $# -gt 0 ]; do
    case "$1" in
        --fleet)          FLEET="$2"; shift 2 ;;
        --no-creds-check) NO_CREDS_CHECK=1; shift ;;
        --dry-run)        DRY_RUN=1; shift ;;
        -h|--help)
            sed -n '2,17p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            echo "install-cron: unknown arg: $1" >&2
            exit 2
            ;;
    esac
done

if [ -z "$FLEET" ]; then
    echo "install-cron: pass --fleet <name> or set CLAUDLOBBY_FLEET" >&2
    exit 2
fi

CLAUDLOBBY_ROOT="${CLAUDLOBBY_ROOT:-$HOME/claudlobby}"
# resolve_bots_dir handles flat local/<fleet> byte-identically + nested vaults.
RUNTIME_BOTS=$(resolve_bots_dir "$FLEET")
LIB="$CLAUDLOBBY_ROOT/lib"

if [ ! -d "$RUNTIME_BOTS" ]; then
    echo "install-cron: $RUNTIME_BOTS not found — run 'claudlobby --fleet $FLEET generate' first" >&2
    exit 1
fi

# Collect bot directories (one per subdir with a bot.conf).
BOTS=()
for conf in "$RUNTIME_BOTS"/*/bot.conf; do
    [ -f "$conf" ] || continue
    BOTS+=("$(dirname "$conf")")
done
NUM_BOTS=${#BOTS[@]}
if [ "$NUM_BOTS" -eq 0 ]; then
    echo "install-cron: no bots found in $RUNTIME_BOTS" >&2
    exit 1
fi

# Compute keepalive stagger: each bot gets a unique offset in a 30-min cycle.
# With N bots, offset_i = i * (60/N) mod 60, and the keepalive fires at
# (offset_i, offset_i + 30) within each hour.
STAGGER_STEP=$((60 / NUM_BOTS))
[ "$STAGGER_STEP" -lt 1 ] && STAGGER_STEP=1

# Fleet-pulse cadence — derive minutes from OBSERVABILITY_PULSE_INTERVAL (seconds),
# read from the first bot's composed bot.conf. Defaults to 300s (5 min).
PULSE_INTERVAL=$(grep -h '^\(export \)\?OBSERVABILITY_PULSE_INTERVAL=' "${BOTS[0]}/bot.conf" 2>/dev/null \
    | head -1 | sed -E 's/^(export )?OBSERVABILITY_PULSE_INTERVAL=//' | tr -d '"' || true)
PULSE_MIN=$(( ${PULSE_INTERVAL:-300} / 60 ))
[ "$PULSE_MIN" -lt 1 ] && PULSE_MIN=1
[ "$PULSE_MIN" -gt 59 ] && PULSE_MIN=59

BEGIN_MARKER="# BEGIN claudlobby:$FLEET"
END_MARKER="# END claudlobby:$FLEET"

# Build the new managed block.
TMPBLOCK=$(safe_mktemp)

{
    echo "$BEGIN_MARKER"
    echo "# Generated by lib/install-cron.sh — do not hand-edit between markers."
    echo "# Re-run install-cron.sh to update; lines outside this block are preserved."
    echo "#"
    echo "# Per-bot keepalive: every 30 min, staggered."
    i=0
    for bot_dir in "${BOTS[@]}"; do
        offset=$(( (i * STAGGER_STEP) % 60 ))
        offset2=$(( (offset + 30) % 60 ))
        # Sort numerically so cron line reads naturally.
        if [ "$offset" -lt "$offset2" ]; then
            schedule="$offset,$offset2 * * * *"
        else
            schedule="$offset2,$offset * * * *"
        fi
        echo "$schedule $LIB/keepalive.sh $bot_dir"
        i=$((i + 1))
    done
    echo "#"
    echo "# Weekly log rotation: Sunday 03:00 — keep last 500 lines of each log."
    echo "0 3 * * 0 $LIB/log-rotate.sh $LIB/keepalive.log $LIB/keepalive-all.log $LIB/bot-sweep-cron.log $LIB/disk-monitor.log $LIB/creds-check.log"
    echo "#"
    echo "# Fleet pulse: external liveness + activity-stuck checks."
    echo "*/$PULSE_MIN * * * * $LIB/fleet-pulse.sh $FLEET"
    if [ "$NO_CREDS_CHECK" != 1 ]; then
        echo "#"
        echo "# Daily credential keepalive: 09:00."
        echo "0 9 * * * $LIB/creds-check.sh"
    fi
    echo "$END_MARKER"
} > "$TMPBLOCK"

# Read existing crontab (or empty if none).
EXISTING=$(crontab -l 2>/dev/null || true)

# Strip any prior block for this fleet.
NEW_CRONTAB=$(awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" '
    $0 == begin { in_block = 1; next }
    $0 == end   { in_block = 0; next }
    !in_block   { print }
' <<<"$EXISTING")

# Append the new block (with a leading blank line if there is existing content).
if [ -n "$NEW_CRONTAB" ]; then
    NEW_CRONTAB="$NEW_CRONTAB"$'\n\n'"$(cat "$TMPBLOCK")"
else
    NEW_CRONTAB="$(cat "$TMPBLOCK")"
fi

if [ "$DRY_RUN" = 1 ]; then
    echo "--- dry-run: would install this crontab ---"
    echo "$NEW_CRONTAB"
    echo "--- end ---"
    exit 0
fi

echo "$NEW_CRONTAB" | crontab -
echo "installed: $NUM_BOTS bot(s), log rotation, disk monitor$([ "$NO_CREDS_CHECK" != 1 ] && echo ', creds-check')"
echo "view: crontab -l"
echo "edit: crontab -e (then preserve the BEGIN/END claudlobby:$FLEET block)"
