"""Shared .env merge intentions and a read-only, value-free preview.

The writer retains its I/O, two reads, errors and logs. Plans hide payloads in
repr; only validated names and counts may cross the preview's output boundary.
"""
from __future__ import annotations

from collections.abc import Iterator
from dataclasses import dataclass, field
from pathlib import Path
import re
import stat
from typing import TYPE_CHECKING

from . import dotenv

if TYPE_CHECKING:
    from .composer import EnvVar


@dataclass(frozen=True)
class EnvMergePlan:
    content: str | None = field(repr=False)
    new_vars: tuple[EnvVar, ...] = field(repr=False)
    rewritten_names: tuple[str, ...] = field(repr=False)


@dataclass(frozen=True)
class ScaffoldRequest:
    path: Path
    header: str = field(repr=False)
    required: list[EnvVar] = field(repr=False)


@dataclass(frozen=True)
class ScaffoldBatch:
    tier: str
    requests: Iterator[ScaffoldRequest] = field(repr=False)


_PRISTINE_STUB_RE = re.compile(r"export ([A-Za-z_]\w*)=")
_COMMENTED_STUB_RE = re.compile(r"^#\s*export ([A-Za-z_]\w*)=", re.MULTILINE)
_VALID_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def plan_env_merge(existing_content: str, existing_keys: set[str], header: str,
                   required: list[EnvVar], provided_upstream: frozenset[str]) -> EnvMergePlan:
    existing_keys = set(existing_keys)
    rewrote_stub = False
    rewritten_names = []
    # dotenv.read skips comment lines, so a stub this function previously
    # commented out is invisible to it and would be appended again on the
    # next run — unbounded growth, once per generate, and reload-fleet.sh
    # runs generate on a daily fleet-wide timer. Count them as present.
    existing_keys |= set(_COMMENTED_STUB_RE.findall(existing_content))
    # Neutralise a stub that was written live BEFORE its var gained an
    # upstream value. `provided_upstream` is otherwise consulted only when a
    # key is first scaffolded, so the ordinary dev loop — generate while
    # iterating on fleet.yaml, obtain the token, fill it in, generate again —
    # leaves the original blanking stub in place forever and reproduces the
    # bug in full. Only an untouched `export FOO=` is rewritten: an empty
    # value the operator typed themselves is indistinguishable from this on
    # disk, so anything carrying a value, a comment, or different spacing is
    # left exactly as found.
    if provided_upstream:
        rewritten_names = [m.group(1) for ln in existing_content.split("\n")
                           if (m := _PRISTINE_STUB_RE.fullmatch(ln.strip())) and m.group(1) in provided_upstream]
        # split("\n"), never splitlines(): the latter also breaks on \x0b,
        # \x0c, \x1c-\x1e, \x85, \u2028 and \u2029, none of which end a
        # line in sh. A secret containing any of them was rewritten as two
        # lines — destroyed in place, and the .env left unsourceable.
        rewritten = [
            (
                f"# {ln}   # already set at a higher .env tier; "
                "uncomment to override for this bot"
                if (_m := _PRISTINE_STUB_RE.fullmatch(ln.strip()))
                and _m.group(1) in provided_upstream
                else ln
            )
            for ln in existing_content.split("\n")
        ]
        rewrote_stub = rewritten != existing_content.split("\n")
        existing_content = "\n".join(rewritten)

    new_vars = [
        ev
        for ev in sorted(required, key=lambda e: e.name)
        if ev.name not in existing_keys
    ]
    if not new_vars and existing_content and not rewrote_stub:
        return EnvMergePlan(None, tuple(new_vars), tuple(rewritten_names))
    lines: list[str] = []
    if existing_content:
        lines.append(existing_content.rstrip("\n"))
    else:
        lines.append(header)
        lines.append("# Generated by claudlobby generate — fill in real values.")
        lines.append("")

    if new_vars:
        lines.append("")
        for ev in new_vars:
            source_note = f" (from {ev.source})" if ev.source else ""
            lines.append(f"# {ev.description}{source_note}")
            if ev.name in provided_upstream:
                # Commented, not live — see the docstring on provided_upstream.
                # The hint must not itself be a blanking stub: uncommenting
                # `# export FOO=` yields an empty value and reproduces exactly
                # the bug this branch exists to prevent. Make it unusable until
                # a value is supplied.
                lines.append(
                    f"# Set at a higher .env tier. To override for this bot only,"
                    f" uncomment and supply a value:\n# export {ev.name}=<value>"
                )
            else:
                lines.append(f"export {ev.name}=")

    return EnvMergePlan("\n".join(lines) + "\n", tuple(new_vars), tuple(rewritten_names))


class PreviewUnavailable(Exception):
    """Fixed public reason; never accepts a raw filesystem/parser exception."""


def _metadata(path: Path) -> int | None:
    absolute = path.absolute()
    if '..' in absolute.parts:
        raise PreviewUnavailable('parent-traversal path is unsupported')
    for node in (*reversed(absolute.parents), absolute):
        try:
            mode = node.lstat().st_mode
        except FileNotFoundError:
            return None
        except OSError:
            raise PreviewUnavailable('unreadable metadata') from None
        if stat.S_ISLNK(mode):
            raise PreviewUnavailable('symlink topology is unsupported')
        if node == absolute:
            if not stat.S_ISREG(mode):
                raise PreviewUnavailable('target is not a regular file')
            return stat.S_IMODE(mode)
        if not stat.S_ISDIR(mode):
            raise PreviewUnavailable('ancestor is not a directory')
    raise PreviewUnavailable('unrecognized metadata')


def _names(names) -> str:
    names = list(names)
    visible = sorted(set(name for name in names if _VALID_NAME.fullmatch(name)))
    hidden = sum(not bool(_VALID_NAME.fullmatch(name)) for name in names)
    text = ', '.join(visible) or 'none'
    return text + (f'; {hidden} invalid name(s) hidden' if hidden else '')


def _upstream_names(paths, tier: str) -> frozenset[str]:
    from .composer import _nonempty_env_names, _upstream_env_paths
    names = set()
    for path in _upstream_env_paths(paths, for_tier=tier):
        if _metadata(path) is not None:
            try:
                names |= _nonempty_env_names(path)
            except (OSError, UnicodeError, ValueError, IndexError):
                raise PreviewUnavailable('upstream env content is unreadable') from None
    return frozenset(names)


def _request_plan(request: ScaffoldRequest, upstream: frozenset[str]):
    mode = _metadata(request.path)
    content, keys = '', set()
    if mode is not None:
        try:
            # The writer intentionally makes two independent reads. Do not
            # substitute a new dotenv parser or assume one read is equivalent.
            content = request.path.read_text()
            keys = set(dotenv.read(request.path))
        except (OSError, UnicodeError, ValueError, IndexError):
            raise PreviewUnavailable('target env content is unreadable') from None
    return plan_env_merge(content, keys, request.header, request.required, upstream), mode


def diff_env_scaffolding(fleet, paths, *, bot_name: str | None = None) -> str:
    from .composer import _env_scaffold_batches
    if bot_name is not None:
        return '\nEnvironment: no environment scaffolding requested by --bot.\n'
    lines = ['\n=== Environment scaffold intentions (values hidden) ===',
             'Ordered intentions; earlier validation or writes may prevent later steps.']
    fleet_uncertain = False
    base = paths.fleet_dir or paths.root
    count = 0
    try:
        for batch in _env_scaffold_batches(fleet, paths):
            upstream, unavailable = frozenset(), None
            conditional = batch.tier == 'bot' and fleet_uncertain
            if not conditional:
                try:
                    upstream = _upstream_names(paths, batch.tier)
                except PreviewUnavailable as exc:
                    unavailable = str(exc)
            for request in batch.requests:
                count += 1
                # These labels come from configured paths, never env contents.
                label = request.path.relative_to(base).as_posix().encode('unicode_escape').decode('ascii')
                if conditional:
                    lines.append(f'{label}: conditional on earlier fleet .env content write or unavailable plan; '
                                 f'{len(request.required)} requested variable(s) ({_names(ev.name for ev in request.required)}); mode 0600 requested')
                    continue
                try:
                    if unavailable:
                        raise PreviewUnavailable(unavailable)
                    plan, mode = _request_plan(request, upstream)
                    write = plan.content is not None
                    action = 'content write' if write else 'content unchanged'
                    mode_action = 'create' if mode is None else ('change' if mode != 0o600 else 'already set')
                    protected = sum(ev.name in upstream for ev in plan.new_vars)
                    lines.append(f'{label}: {action}; additions {len(plan.new_vars)} '
                                 f'({_names(ev.name for ev in plan.new_vars)}); protected new stubs {protected}; '
                                 f'pristine stubs commented {len(plan.rewritten_names)} '
                                 f'({_names(plan.rewritten_names)}); mode 0600 ({mode_action})')
                    if batch.tier == 'fleet' and write:
                        fleet_uncertain = True
                except PreviewUnavailable as exc:
                    lines.append(f'{label}: preview unavailable — {exc}')
                    if batch.tier == 'fleet':
                        fleet_uncertain = True
    except (OSError, UnicodeError, ValueError, TypeError, KeyError, IndexError):
        # Library contract failures are disclosed without source excerpts,
        # parser tokens or exception messages that may contain sensitive data.
        lines.append('Environment scaffold preview unavailable — requirements could not be inspected')
    if not count:
        lines.append('No fleet or bot .env requests were enumerated.')
    lines.append('Scope: existing scaffold policy only; no env values, full-generation or concurrent-change guarantee.')
    return '\n'.join(lines) + '\n'
